#!/usr/bin/env bash

# This script is generated by AGS to apply colors to Hyprland dynamically without a full config reload.
# It uses 'hyprctl keyword' to update specific settings.

hyprctl --batch "\
    keyword general:col.active_border rgb({{ $primary }}) rgb({{ $primaryContainer }}) 45deg ; \
    keyword general:col.inactive_border rgb({{ $surface }}) ; \
    keyword group:groupbar:col.active rgb({{ $primary }}) ; \
    keyword group:groupbar:col.inactive rgb({{ $surface }})"
