-- Hyprland Settings Configuration (Layout, Input, Animations, Decoration)

local settings = {
    general = {
        border_size = 2,
        gaps_in = 2,
        gaps_out = 5,
        resize_on_border = true,
        ["col.active_border"] = "rgba(a0a0a0ee) rgba(606060ee) 45deg",
        ["col.inactive_border"] = "rgba(2a2a2aaa)",
        layout = "dwindle",
        allow_tearing = false,
    },
    master = {
        new_status = "master",
        new_on_top = 1,
        mfact = 0.5,
    },
    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        inactive_opacity = 0.9,
        fullscreen_opacity = 1.0,
        dim_inactive = true,
        dim_strength = 0.1,
        dim_special = 0.8,
        shadow = { enabled = false },
        blur = {
            enabled = true,
            size = 3,
            passes = 3,
            ignore_opacity = true,
            new_optimizations = true,
            special = true,
        },
    },
    animations = {
        enabled = true,
        bezier = { "myBezier, 0.0, 1.0, 0.0, 1.0" },
        animation = {
            "windows, 1, 5, myBezier",
            "windowsOut, 1, 5, default, popin 80%",
            "border, 1, 5, default",
            "borderangle, 1, 5, default",
            "fade, 1, 5, default",
            "workspaces, 1, 3, default",
        },
    },
    input = {
        kb_layout = "ro,us",
        repeat_rate = 50,
        repeat_delay = 300,
        numlock_by_default = true,
        left_handed = false,
        follow_mouse = true,
        float_switch_override_focus = false,
        scroll_factor = 5.0,
        touchpad = {
            disable_while_typing = true,
            natural_scroll = true,
            scroll_factor = 0.4,
            clickfinger_behavior = true,
            middle_button_emulation = false,
            ["tap-to-click"] = true,
            drag_lock = false,
        },
        touchdevice = { enabled = true },
        tablet = { transform = 0, left_handed = 0 },
    },
    gesture = {
        "3, horizontal, workspace",
        "3, up, mod: ALT, float",
        "3, down, mod: ALT, float",
        "3, up, mod: SUPER, scale: 1.5, fullscreen",
        "3, down, mod: SUPER, scale: 1.5, fullscreen",
    },
    group = {
        ["col.border_active"] = "rgba(a0a0a0ee)",
        groupbar = { ["col.active"] = "rgba(a0a0a0ee)" },
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms = true,
        enable_swallow = true,
        swallow_regex = "^(kitty)$",
        focus_on_activate = true,
        initial_workspace_tracking = 0,
        middle_click_paste = false,
    },
    binds = {
        workspace_back_and_forth = true,
        allow_workspace_cycles = true,
        pass_mouse_when_bound = false,
    },
    xwayland = { force_zero_scaling = true },
    cursor = {
        no_hardware_cursors = false,
        enable_hyprcursor = true,
        warp_on_change_workspace = true,
    },
    debug = { disable_logs = false },
}

return settings
