#!/bin/bash
# Generated by switchwall.sh - Don't modify it by yourself.
# Time: vineri 24 iulie EEST 2026, 01:21:27 +0300

pkill -f -9 mpvpaper

for monitor in $(hyprctl monitors -j | jq -r '.[] | .name'); do
    mpvpaper -o "no-audio loop hwdec=auto scale=bilinear interpolation=no video-sync=display-resample panscan=1.0 video-scale-x=1.0 video-scale-y=1.0 video-align-x=0.5 video-align-y=0.5 load-scripts=no" "$monitor" "/home/razvan/Pictures/Wallpapers/.wallpapers/Themes/animated/mylivewallpapers-com-Raiden-Shogun-Winter-4K.mp4" &
    sleep 0.1
done
