#!/usr/bin/env lua

-- Generator script to compile ~/.config/hypr/lua/*.lua into ~/.config/hypr/hyprland.conf

package.path = os.getenv("HOME") .. "/.config/hypr/lua/?.lua;" .. package.path

local env = require("env")
local monitors = require("monitors")
local autostart_data = require("autostart")
local settings = require("settings")
local keybinds = require("keybinds")
local rules = require("rules")

local out = {}

local function emit(str)
    table.insert(out, str or "")
end

emit("# Generated by Hyprland Lua Config Generator")
emit("# Do not edit hyprland.conf directly; modify ~/.config/hypr/lua/*.lua instead")
emit("")
emit("$mainMod = Super")
emit("$files = nautilus")
emit("$terminal = kitty")
emit("$scriptsDir = $HOME/.config/hypr/scripts")
emit("$UserScripts = $HOME/.config/hypr/UserScripts")
emit("")

-- Environment Variables
emit("# Environment Variables")
for k, v in pairs(env) do
    emit(string.format("env = %s,%s", k, v))
end
emit("")

-- Monitors
emit("# Monitors")
for _, mon in ipairs(monitors) do
    emit(string.format("monitor=%s,%s", mon.name, mon.spec))
end
emit("")

-- Autostart
emit("# Autostart Apps & Services")
for _, cmd in ipairs(autostart_data.autostart) do
    emit("exec-once = " .. cmd)
end
for _, cmd in ipairs(autostart_data.shutdown) do
    emit("exec-shutdown = " .. cmd)
end
emit("")

-- Settings helper for tables
local function render_section(name, sec, indent)
    indent = indent or ""
    emit(indent .. name .. " {")
    for k, v in pairs(sec) do
        local prefix = indent .. "  "
        if type(v) == "table" then
            if #v > 0 then
                for _, item in ipairs(v) do
                    emit(prefix .. k .. " = " .. tostring(item))
                end
            else
                render_section(k, v, prefix)
            end
        else
            emit(prefix .. k .. " = " .. tostring(v))
        end
    end
    emit(indent .. "}")
    emit("")
end

emit("# Settings")
for sec_name, sec_val in pairs(settings) do
    if type(sec_val) == "table" then
        if #sec_val > 0 then
            for _, item in ipairs(sec_val) do
                emit(sec_name .. " = " .. tostring(item))
            end
            emit("")
        else
            render_section(sec_name, sec_val)
        end
    end
end

-- Keybindings
emit("# Keybindings")
for _, b in ipairs(keybinds) do
    local btype = b.type or "bind"
    if b.mods ~= "" then
        emit(string.format("%s = %s, %s, %s", btype, b.mods, b.key, b.cmd))
    else
        emit(string.format("%s = , %s, %s", btype, b.key, b.cmd))
    end
end
emit("")

-- Window & Layer Rules
emit("# Window Rules")
for _, r in ipairs(rules.windowrules) do
    emit("windowrule = " .. r)
end
for _, r in ipairs(rules.layerrules) do
    emit("layerrule = " .. r)
end
emit("")

local content = table.concat(out, "\n")
local filepath = os.getenv("HOME") .. "/.config/hypr/hyprland.conf"
local file = io.open(filepath, "w")
if file then
    file:write(content)
    file:close()
    print("Successfully compiled Hyprland Lua config -> " .. filepath)
else
    print("Error writing " .. filepath)
end
